go:
  - 1.8

language: go

install:
  - make

script:
  - make test

after_success:
  test -n "$TRAVIS_TAG" && make release

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      sudo sh -c 'echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi